source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

inhibit_all_warnings!

target 'Example' do
  use_frameworks!

  pod 'GKNavigationBarSwift', :path => '../'
  pod 'TZImagePickerController'

end
